docs(readme): added description new structure and onboarding new product teams
catenax-ng/product-onboarding pull request #2
Opened 2023-01-16 15:28 UTC by FaGru3n

Added documentation after refactoring new structure of onboarding repository

2023-01-24 17:59 UTC, almadigabor requested changes
Read through the first 3 files and added some suggestions with syntactic and semantic fixes. Will check the other files tomorrow.

2023-01-24 17:59 UTC, almadigabor commented on PREREQUISITES.md
> +You had to be invited to our Azure Subscription on [Azure-Portal](https://portal.azure.com/#@catenax.onmicrosoft.com)
```suggestion
You have to be invited to our Azure Subscription on [Azure-Portal](https://portal.azure.com/#@catenax.onmicrosoft.com)
```

2023-01-24 17:59 UTC, almadigabor commented on PREREQUISITES.md
> +Login to Azure on CLI for help, just ask an System Team Internal Member who has allready done that.
```suggestion
Login to Azure on CLI for help, just ask a System Team Internal Member who has already done that.
```

2023-01-24 17:59 UTC, almadigabor commented on PREREQUISITES.md
> +Depending on which terraform run you will about to plan and perform you need to export the desired `TOKEN` from the terraform run to generate the ressources within it.
I'd remove this for easier understanding if the next sentence is modified.

```suggestion
```

2023-01-24 17:59 UTC, almadigabor commented on PREREQUISITES.md
> +For `terraform apply` and `terraform plan` command the following command line variables has to be set:
```suggestion
For `terraform apply` and `terraform plan` command the following command line variables has to be exported from our `Vault` and set:
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +In `cluster` folder are all available clusters, in the `cluster/<clustername>/kustomization.yaml` we describe which product is deployed on the each cluster with the decleared permission level for the
```suggestion
The `cluster` folder contains all available clusters, in the `cluster/<clustername>/kustomization.yaml` we describe on which cluster the products with the declared permissions are deployed.
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +Discription  of the to be added github teams / github repositorys / github repository-teams-mapping can be found in `github/terraform.tfvars` and if we want to create a new Repo/Team/Mapping we need
```suggestion
Description  of the to be added GitHub teams / GitHub repositories / GitHub repository-teams-mapping can be found in `github/terraform.tfvars` and if we want to create a new Repo/Team/Mapping we need to add all of the following.
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +- 'New' Github Teams
```suggestion
- 'New' Github Team
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +More Information can be found under Github Folder: [README.md](github/README.md)
```suggestion
More information can be found under the github folder: [README.md](github/README.md)
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +We are providing for all product-teams vaults with their related Key/Value pairs based on the gh-product-team-name.
```suggestion
We are providing all product-teams `Vault` access with their Secrets Engine where they can store their own  Key/Value pairs based on the `gh-product-team-name`.
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +Discription  of the to be added product vault can be found in `vault/terraform.tfvars`.
```suggestion
Description of the product to be added to vault can be found in `vault/terraform.tfvars`.
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +More Information can be found under Vault folder: [README](vault/README.md)
```suggestion
More information can be found under vault folder: [README](vault/README.md)
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +Only after the merge in Github and the terraform apply have been done, the terraform state is consistent.
```suggestion
Only after the merge in GitHub and the `terraform apply` have been done, the terraform state is consistent, otherwise changes which are applied in parallel by someone else might be deleted again.
```

2023-01-24 17:59 UTC, almadigabor commented on README.md
> +Otherwise changes which are applied in parallel by someone else might be deleted again.
```suggestion
```

2023-01-24 17:59 UTC, almadigabor commented on argocd/README.md
> +To provide a product-team access to the and cluster e.g. devsecops-testing infrastructure following onboarding steps must be performed (all
```suggestion
To provide a product-team access to a cluster (e.g. devsecops-testing) the following onboarding steps must be performed (all
```

2023-01-24 17:59 UTC, almadigabor commented on argocd/README.md
> +with this we provide a
```suggestion
With this we provide a 
```

2023-01-24 17:59 UTC, almadigabor commented on argocd/README.md
> +Create terraform manifests for the new product-team into a separate folder in this `argocd` folder and this will create per default a:
```suggestion
Create terraform manifests for the new product-team into a separate folder inside the `argocd` folder and this will create per default a:
```

2023-01-24 17:59 UTC, almadigabor commented on argocd/README.md
> +Store the manifests in [product-onboarding](https://github.com/catenax-ng/product-onboarding)repo in path `argocd` and an entry based on their permissions in every `cluster/<ClusterEnvironment>/kusto
```suggestion
Store the manifests in [product-onboarding](https://github.com/catenax-ng/product-onboarding) repo in path `argocd` and an entry based on their permissions in every `cluster/<ClusterEnvironment>/kustomization.yaml`  where the new product-team need a new argocd-project. Default is dev and int (named here Hotel-Budapest).
```

2023-01-24 17:59 UTC, almadigabor commented on argocd/README.md
> +To deploy k8s namespace, ArgoCD Project and the AVP secret to on cluster envionment e.g devsecops-testing  you'll have to add a new entry into `cluster/devsecops-testing/kustomization.yaml`
```suggestion
To deploy k8s namespace, ArgoCD Project and the AVP secret to the cluster (e.g devsecops-testing) you'll have to add a new entry to the `cluster/devsecops-testing/kustomization.yaml` file.
```

2023-01-25 07:45 UTC, FaGru3n commented
> Read through the first 3 files and added some suggestions with syntactic and semantic fixes. Will check the other files tomorrow.

Thx @almadigabor updated the most typo's. -  "four eyes see more than two" 😉

2023-01-25 08:28 UTC, almadigabor requested changes
Some small changes for the remaining files.

2023-01-25 08:28 UTC, almadigabor commented on cluster/README.md
> +In `cluster` folder are all available clusters, in the `cluster/<clustername>/kustomization.yaml` we describe which product is deployed on the each cluster with the decleared permission level for the
Just copied this from the main README.md

```suggestion
The `cluster` folder contains all available clusters, in the `cluster/<clustername>/kustomization.yaml` we describe on which cluster the products with the declared permissions are deployed.
```

2023-01-25 08:28 UTC, almadigabor commented on github/README.md
> +**TLDR** one terraform run for all gh-repositorys gh-teams and gh-mapping between repositorys and teams
```suggestion
**TLDR** one terraform run for all gh-repositories, gh-teams and gh-mapping between repositories and teams
```

2023-01-25 08:28 UTC, almadigabor commented on github/README.md
> +In our case we have one Github Organisation which is capable for all github repository information within the catena-x ng for each product.
```suggestion
In our case we have one GitHub Organization which contains all GitHub repository information within
 catena-x ng for each product.
```

2023-01-25 08:28 UTC, almadigabor commented on github/README.md
> +As convention, we decided to for the map key as a combination of repository and team (`<repository-name-team-name>`).
```suggestion
As convention, we decided for the map key to be a combination of repository and team (`<repository-name-team-name>`).
```

2023-01-25 08:28 UTC, almadigabor commented on github/README.md
> +## GitHub Organistation
```suggestion
## GitHub Organization
```

2023-01-25 08:28 UTC, almadigabor commented on github/README.md
> +The following section describes how to handle users, teams and repositories in our GitHub organisation
```suggestion
The following section describes how to handle users, teams and repositories in our GitHub organization
```

2023-01-25 08:28 UTC, almadigabor commented on github/terraform.tfvars
> +# Explanation for the Structure of the Variables with provide for terraform scripts
```suggestion
# Explanation for the structure and variables we provide for terraform scripts
```

2023-01-25 08:28 UTC, almadigabor commented on vault/README.md
> +In our case we have one Vault Cluster which is capable for all Vault information for each cluster and product.
```suggestion
In our case we have one Vault Cluster which contains all secrets for each cluster and product.
```

2023-01-25 08:28 UTC, almadigabor commented on vault/terraform.tfvars
> +# on UI and a technical user for new product
Move one line up

```suggestion
```

2023-01-25 08:28 UTC, almadigabor commented on vault/terraform.tfvars
> +# New Product Object for Vault for authenticate new product gh teams to the ArgoCD deployed Vault
```suggestion
# New product object for product teams to authenticate in Vault. Also contains the name of the machine user, the name of the secret engine and the Kubernetes secret with which the ArgoCD Vault Plugin can authenticate to resolve secret variables.
```

2023-01-25 12:29 UTC, almadigabor approved these changes
Looks good.

2023-02-15 13:34 UTC, SebastianBezold approved these changes

2023-02-15 13:35 UTC, merged